name = "Minceraft S7"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3bbb3089d4a99bc3ff12ad978ef2941aa23589ffaa7244e2c6b4871692e74ed"

[versions]
fabric = "0.116.12"
minecraft = "1.21.1"
neoforge = "21.1.219"
