name = "Minceraft S7"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d857750ceb6ffd39ff3c35689a93bb0ecf8a03a1e5577987ede18f3fe1a69898"

[versions]
fabric = "0.116.12"
minecraft = "1.21.1"
neoforge = "21.1.219"
