name = "Minceraft S7"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fa754f6065a8840e347c8f58eaad664e5a9f0c6a499ebcc74441e55ed98e492"

[versions]
fabric = "0.116.12"
minecraft = "1.21.1"
neoforge = "21.1.219"
