name = "Minceraft S6"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5430f9bc03de2678bf38d3b0b895e7c779ae7ea6090a18a10f689aa217ff9c41"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
