name = "Minceraft S6"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b52de58486de7484b260d4a89afde4a720a576bb4762a5a025febc759fe8ecc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
