name = "Minceraft S6"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ec6ddabf10adab48ddd98cb5679772258809917bbe701a3519b303ffa9ab3da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
